---
global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#sergey_korneev'
