---
- name: Run runner in docker
  hosts: gitlab-ci
  become: true
  tasks:
    - name: Create config directory
      file:
        path: /srv/gitlab-runner/config
        state: directory

    - name: Copy config file
      copy:
        src: files/config.toml
        dest: /srv/gitlab-runner/config/config.toml
        force: no

    - name: Run runner
      docker_container:
        name: gitlab-runner
        image: gitlab/gitlab-runner:latest
        restart_policy: always
        volumes:
          - /srv/gitlab-runner/config:/etc/gitlab-runner
          - /var/run/docker.sock:/var/run/docker.sock
