version: '3.3'

services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db
      monitoring:
      tracing:
    environment:
      - ZIPKIN_ENABLED
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - frontend
      - monitoring
      - tracing
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - backend
      - frontend
      - monitoring
      - tracing
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - backend
      - frontend
      - monitoring
      - tracing
    environment:
      - ZIPKIN_ENABLED

volumes:
  post_db:

networks:
  backend:
  frontend:
  monitoring:
  tracing:
