version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      backend:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - frontend
      - monitoring
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - backend
      - frontend
      - monitoring
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - backend
      - frontend
      - monitoring

volumes:
  post_db:

networks:
  backend:
  frontend:
  monitoring:
